run-dev:
	fvm flutter run --dart-define-from-file=config/env.dev.json

run-prod:
	fvm flutter run --dart-define-from-file=config/env.production.json

build-apk-prod:
	fvm flutter build apk --dart-define-from-file=config/env.production.json